//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nui.MallInfo.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MALLDBEntities : DbContext
    {
        public MALLDBEntities()
            : base("name=MALLDBEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_BASE_CONFIG> T_BASE_CONFIG { get; set; }
        public virtual DbSet<T_BASE_NOTICE> T_BASE_NOTICE { get; set; }
        public virtual DbSet<T_SYS_EVENT> T_SYS_EVENT { get; set; }
        public virtual DbSet<T_SYS_MODULE> T_SYS_MODULE { get; set; }
        public virtual DbSet<T_SYS_ROLEPERMISSION> T_SYS_ROLEPERMISSION { get; set; }
        public virtual DbSet<T_SYS_ROLES> T_SYS_ROLES { get; set; }
        public virtual DbSet<T_SYS_TABLEFIELDS> T_SYS_TABLEFIELDS { get; set; }
        public virtual DbSet<T_SYS_USER> T_SYS_USER { get; set; }
    }
}
