//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nui.MallInfo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BASE_NOTICE
    {
        public int NOTICEID { get; set; }
        public string TITLE { get; set; }
        public string CONTENTS { get; set; }
        public string PUBLISHER { get; set; }
        public Nullable<System.DateTime> SENDTIME { get; set; }
        public Nullable<System.DateTime> EXPIPETIME { get; set; }
        public string EDIT_USER { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
    }
}
