//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nui.MallInfo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_MODULE
    {
        public int MODULEID { get; set; }
        public Nullable<int> M_PARENTID { get; set; }
        public string M_CODE { get; set; }
        public string M_CNAME { get; set; }
        public string M_DIRECTORY { get; set; }
        public string M_LEVEL { get; set; }
        public Nullable<int> M_SORT { get; set; }
        public Nullable<int> M_CLOSE { get; set; }
        public string M_ICON { get; set; }
        public string MEMO_TEXT { get; set; }
        public string EDIT_USER { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
    }
}
