//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nui.MallInfo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_EVENT
    {
        public int EVENTID { get; set; }
        public string E_U_ACCOUNT { get; set; }
        public string E__U_NAME { get; set; }
        public System.DateTime E_DATETIME { get; set; }
        public string E_M_NAME { get; set; }
        public string E_M_CODE { get; set; }
        public string E_FROM { get; set; }
        public int E_TYPE { get; set; }
        public string E_IP { get; set; }
        public string E_RECORD { get; set; }
    }
}
