//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nui.MallInfo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_ROLEPERMISSION
    {
        public int PERMISSIONID { get; set; }
        public Nullable<int> ROLEID { get; set; }
        public Nullable<int> MODULEID { get; set; }
    }
}
