//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nui.MallInfo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_USER
    {
        public int USERID { get; set; }
        public string U_ACCOUNT { get; set; }
        public string U_NAME { get; set; }
        public string U_PASSWORD { get; set; }
        public string U_PHONE { get; set; }
        public string U_EMAIL { get; set; }
        public Nullable<int> U_ROLEID { get; set; }
        public string U_ROLENAME { get; set; }
        public Nullable<int> U_TYPE { get; set; }
        public Nullable<int> U_STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string MEMO_TEXT { get; set; }
        public string EDIT_USER { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
    }
}
